services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dockers_default

  graphql-server:
    build: .
    container_name: graphql-server
    ports:
      - "9001:9000"
    depends_on:
      - mongodb
    networks:
      - dockers_default

networks:
  dockers_default:
    external: true

volumes:
  mongo-data:
